"""Add searchTerms to jobs.json for fuzzy matching."""
import json

SEARCH_TERMS = {
    "arborist": ["tree surgeon", "tree lopper", "tree trimmer", "tree removal"],
    "surgeon": ["doctor", "surgical", "general surgeon", "heart surgeon", "brain surgeon", "orthopaedic surgeon", "orthopedic surgeon", "neurosurgeon", "cardiothoracic surgeon"],
    "diesel-mechanic": ["diesel fitter", "heavy vehicle mechanic", "truck mechanic", "diesel tech", "heavy diesel mechanic"],
    "firefighter": ["fireman", "firewoman", "fire fighter", "firey", "firie"],
    "crane-operator": ["crane driver", "crane rigger", "tower crane operator", "mobile crane operator"],
    "plumber": ["plumbing", "drain specialist", "gasfitter", "gas fitter", "pipe fitter", "pipefitter"],
    "roofer": ["roof tiler", "roof plumber", "roofing contractor", "roof installer"],
    "electrician": ["sparky", "electrical tradesperson", "electrical contractor", "linesman"],
    "glazier": ["glass installer", "window installer", "glass cutter", "window fitter"],
    "midwife": ["birth attendant", "obstetric nurse", "maternity nurse", "doula"],
    "carpenter": ["chippy", "joiner", "cabinetmaker", "cabinet maker", "woodworker", "timber framer"],
    "elevator-installer": ["lift installer", "elevator mechanic", "lift technician", "elevator technician", "lift mechanic"],
    "paramedic": ["EMT", "emergency medical technician", "ambulance officer", "ambo", "first responder"],
    "hvac-technician": ["HVAC tech", "air conditioning technician", "AC technician", "heating technician", "refrigeration mechanic", "aircon tech"],
    "kindergarten-teacher": ["kindy teacher", "preschool teacher", "early childhood teacher", "early childhood educator", "ECE teacher", "prep teacher"],
    "speech-pathologist": ["speech therapist", "speech language pathologist", "SLP", "speech and language therapist"],
    "dentist": ["dental surgeon", "oral surgeon", "orthodontist", "endodontist", "periodontist"],
    "special-education-teacher": ["special ed teacher", "SPED teacher", "special needs teacher", "learning support teacher", "inclusion teacher", "resource teacher"],
    "welder": ["boilermaker", "fabricator", "metal fabricator", "welding technician", "MIG welder", "TIG welder"],
    "athletic-trainer": ["sports trainer", "sports therapist", "athletic therapist", "team trainer"],
    "landscaper": ["gardener", "landscape gardener", "groundskeeper", "grounds keeper", "lawn care", "greenkeeper"],
    "physical-therapist": ["physiotherapist", "physio", "PT", "physical therapy assistant", "rehabilitation therapist"],
    "auto-mechanic": ["car mechanic", "automotive technician", "motor mechanic", "mechanic", "auto technician", "car technician"],
    "occupational-therapist": ["OT", "occupational therapy", "rehab therapist"],
    "marine-biologist": ["ocean scientist", "marine scientist", "marine ecologist", "aquatic biologist", "marine researcher"],
    "social-worker": ["case worker", "case manager", "community worker", "welfare worker", "child protection worker", "youth worker"],
    "veterinarian": ["vet", "animal doctor", "veterinary surgeon", "small animal vet", "large animal vet"],
    "construction-worker": ["builder", "labourer", "laborer", "construction labourer", "building labourer", "tradesman"],
    "psychologist": ["clinical psychologist", "counselling psychologist", "counseling psychologist", "therapist", "psych", "behavioural psychologist", "behavioral psychologist", "neuropsychologist", "educational psychologist", "school psychologist", "organisational psychologist"],
    "chef": ["head chef", "sous chef", "executive chef", "line cook", "pastry chef", "cook", "short order cook"],
    "locksmith": ["lock technician", "security locksmith", "safe technician"],
    "air-traffic-controller": ["ATC", "air traffic control", "flight controller"],
    "archaeologist": ["archaeology", "field archaeologist", "excavation specialist"],
    "personal-trainer": ["PT", "fitness trainer", "gym instructor", "fitness coach", "strength coach", "personal fitness trainer"],
    "tattoo-artist": ["tattooist", "tattoo designer", "ink artist", "tattooer", "body artist"],
    "hair-stylist": ["hairdresser", "barber", "hair dresser", "colourist", "colorist", "hair colourer", "salon stylist"],
    "musician": ["singer", "guitarist", "drummer", "bassist", "pianist", "musician", "performer", "session musician", "band member", "instrumentalist", "DJ", "disc jockey"],
    "police-officer": ["cop", "detective", "constable", "sergeant", "law enforcement", "police", "officer"],
    "wedding-planner": ["bridal planner", "wedding coordinator", "bridal consultant", "event coordinator"],
    "film-director": ["movie director", "director", "filmmaker", "film maker", "showrunner", "TV director"],
    "funeral-director": ["mortician", "undertaker", "funeral home director", "funeral planner"],
    "nurse": ["registered nurse", "RN", "nursing", "ward nurse", "emergency nurse", "ICU nurse", "theatre nurse", "surgical nurse", "practice nurse"],
    "park-ranger": ["ranger", "national park ranger", "wildlife ranger", "conservation officer", "game warden"],
    "bartender": ["barman", "barmaid", "bar staff", "mixologist", "cocktail bartender"],
    "diplomat": ["foreign service officer", "ambassador", "consular officer", "embassy staff"],
    "nutritionist": ["dietitian", "dietician", "nutritional therapist", "clinical dietitian", "sports nutritionist"],
    "school-counselor": ["school counsellor", "guidance counselor", "guidance counsellor", "student counselor", "student counsellor", "college counselor"],
    "sports-coach": ["coach", "football coach", "basketball coach", "soccer coach", "athletics coach", "swim coach", "tennis coach", "sports trainer"],
    "chiropractor": ["chiro", "spinal specialist", "back specialist"],
    "doctor-gp": ["GP", "general practitioner", "family doctor", "family physician", "primary care doctor", "primary care physician", "doctor", "medical doctor", "MD"],
    "florist": ["flower arranger", "floral designer", "flower shop owner"],
    "museum-curator": ["curator", "gallery curator", "art curator", "collections manager", "museum director"],
    "waiter": ["waitress", "server", "wait staff", "food server", "restaurant server", "waiter", "waitstaff"],
    "geologist": ["mining geologist", "petroleum geologist", "geological engineer", "earth scientist", "hydrogeologist"],
    "pilot": ["airline pilot", "commercial pilot", "captain", "first officer", "co-pilot", "helicopter pilot", "charter pilot"],
    "art-teacher": ["art instructor", "visual arts teacher", "art educator", "painting teacher", "drawing teacher"],
    "high-school-teacher": ["secondary teacher", "secondary school teacher", "high school educator", "maths teacher", "math teacher", "english teacher", "science teacher", "history teacher", "teacher"],
    "construction-manager": ["site manager", "project superintendent", "building supervisor", "site supervisor", "site foreman", "construction superintendent"],
    "environmental-scientist": ["environmental consultant", "environmental engineer", "ecologist", "sustainability consultant", "environmental analyst"],
    "optometrist": ["eye doctor", "optician", "eye specialist", "vision specialist"],
    "flight-attendant": ["cabin crew", "steward", "stewardess", "air hostess", "airline attendant"],
    "urban-planner": ["city planner", "town planner", "regional planner", "planning officer", "urban designer"],
    "civil-engineer": ["structural engineer", "infrastructure engineer", "transportation engineer", "geotechnical engineer", "water engineer"],
    "esl-teacher": ["ESL instructor", "English teacher", "TESOL teacher", "TEFL teacher", "English as a second language", "EAL teacher", "language teacher"],
    "sound-engineer": ["audio engineer", "recording engineer", "mix engineer", "live sound engineer", "studio engineer", "audio technician"],
    "barista": ["coffee maker", "cafe worker", "coffee artist"],
    "pharmacist": ["chemist", "dispensing pharmacist", "hospital pharmacist", "community pharmacist", "clinical pharmacist"],
    "housekeeper": ["cleaner", "house cleaner", "maid", "domestic cleaner", "room attendant", "hotel housekeeper", "cleaning lady"],
    "mechanical-engineer": ["mechanical designer", "design engineer", "HVAC engineer", "automotive engineer", "manufacturing engineer"],
    "music-producer": ["record producer", "beat maker", "studio producer", "audio producer"],
    "interior-designer": ["interior decorator", "interior stylist", "home decorator", "interior architect", "space planner"],
    "architect": ["building designer", "residential architect", "commercial architect", "landscape architect", "architectural designer"],
    "university-professor": ["professor", "lecturer", "academic", "college professor", "associate professor", "assistant professor", "tenure-track professor", "uni lecturer"],
    "pathologist": ["anatomical pathologist", "clinical pathologist", "histopathologist", "forensic pathologist"],
    "radiologist": ["diagnostic radiologist", "interventional radiologist", "imaging specialist", "radiology doctor"],
    "dental-hygienist": ["oral hygienist", "dental therapist", "teeth cleaner"],
    "event-planner": ["event manager", "event coordinator", "conference organiser", "conference organizer", "event organiser"],
    "robotics-engineer": ["robotics developer", "automation engineer", "robot designer", "mechatronics engineer"],
    "sports-coach-head": ["head coach", "manager", "team manager", "sporting director", "athletics director"],
    "compliance-officer": ["compliance manager", "regulatory affairs", "compliance analyst", "regulatory compliance", "risk and compliance"],
    "nurse-practitioner": ["NP", "advanced practice nurse", "APN", "clinical nurse specialist", "CNS", "nurse specialist"],
    "real-estate-agent": ["realtor", "real estate salesperson", "property agent", "estate agent", "real estate broker", "buyer's agent", "listing agent", "property manager"],
    "research-scientist": ["researcher", "lab researcher", "principal investigator", "PI", "postdoc", "post-doc", "postdoctoral researcher"],
    "audiologist": ["hearing specialist", "hearing aid specialist", "audiology"],
    "forensic-scientist": ["forensics", "crime scene investigator", "CSI", "forensic analyst", "crime lab technician", "forensic technician"],
    "marketing-manager": ["marketing director", "brand manager", "head of marketing", "marketing lead", "CMO", "digital marketing manager", "marketing coordinator"],
    "cybersecurity-analyst": ["security analyst", "infosec", "information security analyst", "SOC analyst", "penetration tester", "pen tester", "ethical hacker", "security engineer", "cybersecurity director", "director of cybersecurity", "CISO", "security director"],
    "hotel-manager": ["hospitality manager", "resort manager", "front office manager", "general manager hotel"],
    "hr-manager": ["human resources manager", "HR director", "people manager", "people and culture", "talent manager", "head of HR", "HR business partner", "HRBP", "human resources"],
    "management-consultant": ["strategy consultant", "business consultant", "advisory", "consulting", "McKinsey", "BCG", "Bain"],
    "corporate-trainer": ["learning and development", "L&D", "training specialist", "training coordinator", "professional development", "instructional designer"],
    "podcast-producer": ["podcast editor", "podcast manager", "audio producer", "show producer"],
    "sales-manager": ["sales director", "head of sales", "VP sales", "account manager", "sales lead", "sales executive", "BDM", "business development manager"],
    "librarian": ["library assistant", "information specialist", "library technician", "research librarian", "children's librarian"],
    "project-manager": ["PM", "program manager", "programme manager", "scrum master", "delivery manager", "project coordinator", "project lead", "senior program manager", "senior project manager"],
    "game-designer": ["game developer", "game dev", "level designer", "systems designer", "gameplay designer", "narrative designer"],
    "devops-engineer": ["site reliability engineer", "SRE", "platform engineer", "infrastructure engineer", "cloud engineer", "systems engineer"],
    "insurance-agent": ["insurance broker", "insurance advisor", "insurance salesperson", "insurance consultant", "underwriting agent"],
    "product-manager": ["product owner", "PO", "product lead", "product director", "head of product", "product analyst"],
    "public-relations-specialist": ["PR specialist", "PR manager", "communications manager", "media relations", "comms manager", "publicist", "press officer"],
    "tutor": ["private tutor", "online tutor", "academic tutor", "maths tutor", "math tutor", "English tutor", "tutoring"],
    "fashion-designer": ["clothing designer", "apparel designer", "garment designer", "textile designer", "costume designer"],
    "photographer": ["wedding photographer", "portrait photographer", "commercial photographer", "photo journalist", "photojournalist", "event photographer"],
    "data-scientist": ["data analyst", "machine learning engineer", "ML engineer", "AI engineer", "data engineer", "analytics", "big data"],
    "market-researcher": ["consumer researcher", "UX researcher", "user researcher", "insights analyst", "market analyst", "research analyst"],
    "operations-manager": ["ops manager", "COO", "chief operating officer", "operations director", "head of operations"],
    "screenwriter": ["script writer", "scriptwriter", "screenplay writer", "TV writer", "playwright"],
    "ux-designer": ["UI designer", "UX/UI designer", "user experience designer", "interaction designer", "product designer", "UI/UX", "experience designer", "ux director", "director of ux", "head of design", "design director"],
    "business-analyst": ["BA", "systems analyst", "business systems analyst", "requirements analyst", "process analyst"],
    "financial-analyst": ["finance analyst", "FP&A", "financial planning", "investment analyst", "equity analyst", "credit analyst"],
    "software-engineer": ["software developer", "programmer", "coder", "dev", "backend developer", "frontend developer", "full stack developer", "fullstack", "software dev", "SWE", "application developer", "systems developer"],
    "video-editor": ["film editor", "post-production", "post production", "video producer", "editor", "colour grader", "color grader"],
    "animator": ["3D animator", "2D animator", "motion designer", "motion graphics artist", "character animator", "VFX artist"],
    "journalist": ["reporter", "news reporter", "correspondent", "investigative journalist", "features writer", "news writer"],
    "logistics-coordinator": ["logistics manager", "supply chain coordinator", "shipping coordinator", "dispatch coordinator", "freight coordinator"],
    "supply-chain-analyst": ["supply chain manager", "procurement analyst", "supply chain planner", "demand planner", "inventory analyst"],
    "technical-writer": ["tech writer", "documentation writer", "API writer", "content developer", "information developer"],
    "truck-driver": ["trucker", "truck driver", "lorry driver", "delivery driver", "HGV driver", "CDL driver", "semi driver", "long haul driver", "courier"],
    "teaching-assistant": ["teacher aide", "teacher's aide", "classroom assistant", "learning support assistant", "LSA", "education assistant", "TA"],
    "advertising-executive": ["ad executive", "account executive", "creative director", "ad agency", "advertising manager"],
    "economist": ["economic analyst", "economic researcher", "economic advisor", "policy analyst"],
    "office-manager": ["admin manager", "administration manager", "facilities manager", "office administrator", "office admin"],
    "retail-manager": ["store manager", "shop manager", "retail supervisor", "assistant manager retail", "department manager"],
    "executive-assistant": ["EA", "personal assistant", "PA", "executive secretary", "C-suite assistant"],
    "lab-technician": ["laboratory technician", "lab tech", "lab assistant", "research assistant", "science technician"],
    "voice-actor": ["voiceover artist", "voice over", "VO artist", "narrator", "voice talent"],
    "web-developer": ["web dev", "frontend developer", "front-end developer", "full stack developer", "web designer", "WordPress developer", "Shopify developer", "website builder", "website creator", "website developer"],
    "actuary": ["actuarial analyst", "actuarial consultant", "insurance mathematician", "risk analyst"],
    "quality-assurance-tester": ["QA tester", "QA engineer", "test engineer", "quality analyst", "software tester", "test analyst", "SDET", "quality control", "security quality control"],
    "video-game-tester": ["game tester", "QA game tester", "playtest", "game QA", "bug tester"],
    "customer-service-manager": ["customer success manager", "CSM", "customer experience manager", "CX manager", "support manager", "call centre manager", "call center manager"],
    "financial-planner": ["financial advisor", "financial adviser", "wealth manager", "financial consultant", "certified financial planner", "CFP", "wealth advisor"],
    "freight-broker": ["freight forwarder", "customs broker", "shipping broker", "logistics broker", "freight agent"],
    "network-administrator": ["network engineer", "sysadmin", "systems administrator", "network admin", "IT administrator", "infrastructure admin"],
    "optician": ["dispensing optician", "optical dispenser", "eyewear specialist", "lens technician"],
    "purchasing-agent": ["procurement officer", "procurement specialist", "buyer", "purchasing officer", "procurement manager", "supply officer"],
    "accountant": ["CPA", "chartered accountant", "tax accountant", "management accountant", "financial accountant", "accounting"],
    "database-administrator": ["DBA", "database engineer", "data administrator", "database manager", "database developer"],
    "radio-broadcaster": ["radio host", "radio presenter", "radio DJ", "radio announcer", "on-air personality", "breakfast host"],
    "technical-support-specialist": ["tech support", "help desk", "helpdesk", "support technician", "desktop support", "IT help desk"],
    "illustrator": ["book illustrator", "editorial illustrator", "children's illustrator", "concept artist", "digital illustrator", "comic artist"],
    "pharmacy-technician": ["pharmacy assistant", "dispensary technician", "pharmacy tech", "dispensary assistant"],
    "recruitment-consultant": ["recruiter", "headhunter", "talent acquisition", "TA specialist", "staffing consultant", "employment agent"],
    "auditor": ["internal auditor", "external auditor", "audit manager", "compliance auditor", "financial auditor", "IT auditor"],
    "loan-officer": ["lending officer", "mortgage officer", "credit officer", "lending specialist", "loan consultant"],
    "sports-journalist": ["sports reporter", "sports writer", "sports broadcaster", "sports commentator", "sports anchor"],
    "claims-adjuster": ["loss adjuster", "insurance adjuster", "claims assessor", "claims investigator"],
    "copywriter": ["ad copywriter", "creative writer", "advertising writer", "brand writer", "copy editor"],
    "it-support-specialist": ["IT support", "tech support", "help desk analyst", "desktop support", "IT helpdesk", "IT technician"],
    "bank-teller": ["bank clerk", "banking officer", "bank cashier", "customer service officer bank"],
    "administrative-assistant": ["admin assistant", "office assistant", "receptionist", "secretary", "admin officer", "clerical officer", "admin support"],
    "drafter": ["draftsperson", "draughtsperson", "CAD drafter", "CAD operator", "technical drafter", "architectural drafter"],
    "insurance-underwriter": ["underwriter", "risk assessor", "insurance analyst", "commercial underwriter"],
    "medical-coder": ["clinical coder", "health information coder", "medical coding specialist", "ICD coder", "HIM specialist"],
    "social-media-manager": ["social media coordinator", "social media specialist", "community manager", "digital content manager", "social media strategist"],
    "content-writer": ["blog writer", "content creator", "content strategist", "web writer", "content marketer", "blogger"],
    "translator": ["interpreter", "linguist", "localiser", "localizer", "translation specialist", "language specialist"],
    "tax-preparer": ["tax agent", "tax consultant", "tax advisor", "tax professional", "tax return preparer"],
    "medical-lab-technician": ["medical laboratory scientist", "pathology technician", "medical scientist", "lab scientist", "clinical laboratory technician"],
    "proofreader": ["copy editor", "editor", "sub-editor", "subeditor", "manuscript editor"],
    "graphic-designer": ["visual designer", "brand designer", "layout designer", "digital designer", "creative designer", "design", "designer"],
    "news-anchor": ["newsreader", "news presenter", "TV presenter", "news host", "anchor", "anchorman", "anchorwoman"],
    "production-planner": ["production scheduler", "manufacturing planner", "production controller", "materials planner"],
    "inventory-manager": ["stock controller", "warehouse manager", "inventory controller", "stock manager", "inventory analyst"],
    "patent-examiner": ["patent analyst", "intellectual property examiner", "IP examiner", "patent reviewer"],
    "scheduling-coordinator": ["scheduler", "appointment coordinator", "booking coordinator", "rostering officer", "roster coordinator"],
    "credit-analyst": ["credit officer", "credit assessor", "credit risk analyst", "lending analyst"],
    "front-desk-receptionist": ["receptionist", "front desk clerk", "front office", "front desk agent", "hotel receptionist", "medical receptionist"],
    "stock-analyst": ["equity analyst", "investment analyst", "securities analyst", "research analyst finance", "stock broker", "stockbroker"],
    "survey-researcher": ["survey analyst", "research associate", "polling analyst", "opinion researcher"],
    "desktop-publisher": ["DTP operator", "layout artist", "page designer", "publication designer"],
    "mortgage-broker": ["home loan broker", "mortgage advisor", "mortgage consultant", "home loan specialist"],
    "bookkeeper": ["BAS agent", "accounts clerk", "accounts officer", "bookkeeping", "ledger clerk"],
    "billing-specialist": ["billing clerk", "billing coordinator", "accounts receivable", "AR clerk", "revenue specialist"],
    "loan-processor": ["mortgage processor", "loan coordinator", "lending processor", "loan administrator"],
    "payroll-specialist": ["payroll officer", "payroll clerk", "payroll administrator", "payroll coordinator", "payroll manager"],
    "legal-secretary": ["legal assistant", "law clerk", "legal admin", "legal support"],
    "statistical-assistant": ["statistics assistant", "data assistant", "research assistant stats", "statistical analyst"],
    "paralegal": ["legal assistant", "law clerk", "litigation support", "legal research assistant"],
    "title-examiner": ["title searcher", "title officer", "title analyst", "land title examiner"],
    "claims-processor": ["claims clerk", "claims administrator", "insurance claims processor", "claims handler"],
    "travel-agent": ["travel consultant", "travel advisor", "travel planner", "holiday consultant", "travel specialist"],
    "word-processor-operator": ["word processor", "document processor", "typing clerk", "word processing operator"],
    "order-clerk": ["order processor", "order entry clerk", "sales order clerk", "purchase order clerk"],
    "correspondence-clerk": ["correspondence officer", "letter writer", "mail clerk", "communications clerk"],
    "telephone-operator": ["phone operator", "switchboard assistant", "telecommunications operator", "PBX operator"],
    "file-clerk": ["filing clerk", "records clerk", "records officer", "document clerk", "archive clerk"],
    "textile-worker": ["garment worker", "sewing machine operator", "fabric worker", "textile operator"],
    "photo-retoucher": ["image editor", "photo editor", "retouching artist", "digital retoucher", "colour corrector"],
    "parking-lot-attendant": ["parking attendant", "car park attendant", "valet", "valet parker", "parking officer"],
    "factory-quality-inspector": ["quality inspector", "QC inspector", "quality control", "quality checker", "QA inspector"],
    "fast-food-cook": ["fast food worker", "McDonald's worker", "kitchen hand", "fry cook", "grill cook", "fast food crew"],
    "basic-bookkeeper": ["junior bookkeeper", "assistant bookkeeper", "bookkeeping assistant", "accounts assistant"],
    "print-shop-operator": ["print operator", "printing press operator", "digital printer", "print technician"],
    "assembly-line-worker": ["factory worker", "production worker", "line worker", "manufacturing worker", "production operator", "assembly worker"],
    "medical-transcriptionist": ["medical typist", "clinical transcriptionist", "healthcare transcriptionist"],
    "warehouse-picker": ["warehouse worker", "picker packer", "pick packer", "warehouse operative", "order picker", "fulfillment associate"],
    "data-entry-clerk": ["data entry operator", "data processor", "keyboard operator", "data entry specialist", "data clerk"],
    "transcriptionist": ["transcriber", "typist", "audio transcriber", "legal transcriptionist", "court reporter"],
    "document-scanner": ["document imaging operator", "scanning clerk", "digitisation operator", "digitization operator"],
    "postal-sorter": ["mail sorter", "postal worker", "mail handler", "letter sorter", "mail processing clerk"],
    "cashier": ["checkout operator", "register operator", "till operator", "point of sale", "POS operator", "shop assistant"],
    "invoice-processor": ["accounts payable clerk", "AP clerk", "invoice clerk", "payment processor"],
    "meter-reader": ["utility reader", "gas meter reader", "electricity meter reader", "utility inspector"],
    "mail-room-clerk": ["mailroom clerk", "mail handler", "mail sorter", "postal clerk"],
    "toll-booth-operator": ["toll collector", "toll attendant", "toll plaza operator"],
    "typist": ["copy typist", "audio typist", "typing clerk", "word processor"],
    "switchboard-operator": ["telephone operator", "PBX operator", "receptionist switchboard", "phone operator"],
    "sports-scorekeeper": ["scorekeeper", "scorer", "statistician sports", "official scorer"],
    "library-catalog-clerk": ["library clerk", "library assistant", "cataloguer", "cataloger", "library technician"],
    "telephone-survey-interviewer": ["survey caller", "telephone interviewer", "phone surveyor", "market research interviewer", "CATI interviewer"],
    "map-drafter": ["cartographer", "map maker", "mapmaker", "GIS technician", "geospatial analyst"],
    "telemarketer": ["cold caller", "telesales", "phone sales", "outbound caller", "telephone sales"],
    "travel-booking-agent": ["booking agent", "reservations agent", "travel reservationist", "online travel agent"],
    "check-processing-clerk": ["cheque processing clerk", "payment processing clerk", "bank processing clerk"],
    "ticket-agent": ["booking clerk", "ticketing agent", "reservation agent", "airline agent", "box office clerk"],
    "photo-lab-technician": ["photo lab tech", "darkroom technician", "photo processor", "film developer"],
    "directory-assistance-operator": ["directory enquiries", "information operator", "411 operator"],
    "classified-ad-taker": ["classified advertising clerk", "ad taker", "advertising clerk"],
    # Batch 2 (from original add_new_jobs.py)
    "paediatrician": ["pediatrician", "children's doctor", "child doctor", "kids doctor", "baby doctor", "child specialist"],
    "housewife": ["stay-at-home mum", "stay-at-home mom", "stay-at-home parent", "homemaker", "sahm", "domestic worker", "stay at home mum", "stay at home mom", "stay at home parent"],
    "lawyer": ["solicitor", "barrister", "attorney", "legal counsel", "legal advisor", "corporate lawyer", "criminal lawyer", "family lawyer", "litigation lawyer"],
    "farmer": ["grazier", "rancher", "crop farmer", "dairy farmer", "cattle farmer", "agriculture worker", "pastoralist", "station hand"],
    "retail-sales-assistant": ["shop assistant", "retail worker", "sales associate", "store clerk", "shop worker", "retail associate", "sales clerk"],
    "childcare-worker": ["daycare worker", "early childhood educator", "ECE", "nursery worker", "creche worker", "child carer", "nanny", "au pair"],
    "aged-care-worker": ["elderly care worker", "nursing home worker", "care assistant", "personal care assistant", "PCA", "support worker", "home care worker", "aged care nurse"],
    "security-guard": ["security officer", "bouncer", "door staff", "loss prevention", "security personnel", "night watchman"],
    "bus-driver": ["coach driver", "transit driver", "public transport driver", "shuttle driver", "school bus driver"],
    "cleaner": ["janitor", "custodian", "office cleaner", "commercial cleaner", "house cleaner", "domestic cleaner", "cleaning lady", "sanitation worker"],
    "rideshare-driver": ["uber driver", "lyft driver", "taxi driver", "cab driver", "ola driver", "ride-hail driver", "private hire driver"],
    "mining-worker": ["miner", "mine worker", "FIFO worker", "underground miner", "open cut miner", "pit worker", "drill operator", "mining operator"],
    "nail-technician": ["nail artist", "manicurist", "nail tech", "pedicurist", "nail salon worker"],
    "makeup-artist": ["MUA", "beauty therapist", "cosmetologist", "beauty consultant", "bridal makeup artist", "film makeup artist", "special effects makeup"],
    "electrical-engineer": ["EE", "electronics engineer", "power engineer", "electrical designer", "circuit engineer", "power systems engineer"],
    "primary-school-teacher": ["elementary school teacher", "grade school teacher", "primary teacher", "year 1 teacher", "year 2 teacher", "year 3 teacher", "year 4 teacher", "year 5 teacher", "year 6 teacher"],
    # Batch 3 — new jobs added 2026-04-03
    "business-manager": ["business manager", "general business manager", "business operations manager"],
    "clinic-manager": ["clinic manager", "practice manager", "medical practice manager", "health clinic manager", "allied health manager"],
    "general-manager": ["general manager", "GM", "site manager", "branch GM"],
    "regional-manager": ["regional manager", "area manager", "district manager", "territory manager"],
    "store-manager": ["store manager", "shop manager", "retail store manager", "outlet manager"],
    "restaurant-manager": ["restaurant manager", "venue manager", "hospitality manager", "food and beverage manager", "F&B manager", "cafe manager"],
    "warehouse-manager": ["warehouse manager", "distribution centre manager", "DC manager", "logistics warehouse manager", "fulfilment manager"],
    "branch-manager": ["branch manager", "bank branch manager", "bank manager"],
    "dental-assistant": ["dental assistant", "dental nurse", "dental chair assistant", "dental surgery assistant"],
    "veterinary-nurse": ["vet nurse", "veterinary nurse", "veterinary technician", "vet tech", "animal nurse", "veterinary assistant"],
    "aged-care-nurse": ["aged care nurse", "geriatric nurse", "nursing home nurse", "elderly care nurse", "residential care nurse"],
    "mental-health-nurse": ["mental health nurse", "psychiatric nurse", "psych nurse", "MHN", "community mental health nurse"],
    "disability-support-worker": ["disability support worker", "DSW", "support worker", "NDIS worker", "disability carer", "care worker"],
    "sonographer": ["sonographer", "ultrasound technician", "ultrasound tech", "diagnostic sonographer", "medical sonographer"],
    "orthotist": ["orthotist", "prosthetist", "orthotist prosthetist", "O&P", "orthotic technician", "prosthetic technician"],
    "boilermaker": ["boilermaker", "boiler welder", "structural welder", "pressure vessel welder"],
    "scaffolder": ["scaffolder", "scaffold erector", "scaffolding worker"],
    "concreter": ["concreter", "concrete finisher", "concrete worker", "concrete layer", "cement worker"],
    "plasterer": ["plasterer", "gyprocker", "drywall installer", "renderer", "plaster worker", "solid plasterer"],
    "cabinet-maker": ["cabinet maker", "cabinetmaker", "joiner", "kitchen maker", "furniture maker", "shopfitter"],
    "auto-electrician": ["auto electrician", "automotive electrician", "vehicle electrician", "car electrician"],
    "fitter-and-turner": ["fitter and turner", "fitter", "turner", "machinist", "mechanical fitter", "maintenance fitter"],
    "forklift-operator": ["forklift operator", "forklift driver", "forkie", "fork truck operator", "reach truck operator", "warehouse forklift"],
    "accounts-receivable-clerk": ["accounts receivable clerk", "AR clerk", "accounts receivable officer", "credit control clerk", "collections clerk"],
    "accounts-payable-clerk": ["accounts payable clerk", "AP clerk", "accounts payable officer", "creditors clerk"],
    "receptionist": ["receptionist", "front desk", "front of house", "reception staff"],
    "office-administrator": ["office administrator", "office admin", "admin officer", "administrative officer", "office coordinator"],
    "machine-learning-engineer": ["machine learning engineer", "ML engineer", "MLE", "AI engineer", "deep learning engineer"],
    "mobile-app-developer": ["mobile app developer", "iOS developer", "Android developer", "mobile developer", "app developer", "React Native developer", "Flutter developer"],
    "frontend-developer": ["frontend developer", "front-end developer", "front end developer", "UI developer", "React developer", "Vue developer", "Angular developer"],
    "backend-developer": ["backend developer", "back-end developer", "back end developer", "server-side developer", "API developer", "Node.js developer", "Python developer", "Java developer"],
    "systems-administrator": ["systems administrator", "sysadmin", "system administrator", "IT administrator", "infrastructure admin", "Linux admin", "Windows admin"],
    "it-manager": ["IT manager", "information technology manager", "IT director", "technology manager", "head of IT"],
    "scrum-master": ["scrum master", "agile coach", "agile facilitator", "scrum coach", "delivery lead"],
    "mortgage-processor": ["mortgage processor", "loan processor", "home loan processor", "mortgage administrator", "lending processor"],
    "conveyancer": ["conveyancer", "conveyancing clerk", "property lawyer", "settlement agent", "conveyancing solicitor"],
    "migration-agent": ["migration agent", "immigration consultant", "immigration agent", "visa consultant", "registered migration agent", "MARA agent"],
    "property-manager": ["property manager", "real estate property manager", "rental manager", "strata manager", "building manager", "facilities manager"],
    "building-inspector": ["building inspector", "building certifier", "building surveyor", "construction inspector", "code compliance inspector", "BCA inspector"],
    "quantity-surveyor": ["quantity surveyor", "QS", "cost estimator", "construction estimator", "cost planner", "cost consultant"],
    "library-assistant": ["library assistant", "library technician", "library aide", "library clerk", "library officer"],
    "youth-worker": ["youth worker", "youth support worker", "youth development worker", "youth mentor", "youth case worker"],
    "community-development-officer": ["community development officer", "CDO", "community engagement officer", "community worker", "community coordinator"],
    "education-coordinator": ["education coordinator", "training coordinator", "learning coordinator", "program coordinator", "course coordinator", "RTO coordinator"],
    "barber": ["barber", "men's hairdresser", "barbershop", "men's barber"],
    "flight-dispatcher": ["flight dispatcher", "airline dispatcher", "flight operations officer", "aircraft dispatcher", "flight planner"],
    "air-conditioning-installer": ["air conditioning installer", "aircon installer", "HVAC installer", "AC installer", "split system installer", "refrigeration mechanic"],
    "fitness-instructor": ["fitness instructor", "group fitness instructor", "gym instructor", "exercise instructor", "aerobics instructor", "spin instructor", "yoga instructor", "pilates instructor"],
    "call-centre-agent": ["call centre agent", "call center agent", "contact centre agent", "phone operator", "customer service agent", "inbound call agent", "outbound call agent"],
    "courier": ["courier", "delivery driver", "parcel delivery", "courier driver", "bike courier", "last mile delivery"],
    "sous-chef": ["sous chef", "second chef", "assistant head chef", "senior chef", "chef de partie", "CDP", "line cook supervisor"],
    "pastry-chef": ["pastry chef", "baker chef", "patissier", "dessert chef", "cake decorator", "pastry cook"],
    # Batch 4 — new jobs from Supabase search gaps (2026-04-03)
    "sales-representative": ["sales", "sales rep", "sales representative", "BDR", "SDR", "account executive", "inside sales", "outside sales", "B2B sales", "business development", "sales associate", "sales consultant"],
    "account-manager": ["account manager", "client manager", "key account manager", "customer success manager", "relationship manager", "client services", "client relations", "KAM"],
    "violinist": ["violin", "violinist", "cellist", "cello", "orchestra", "symphony", "chamber musician", "viola", "double bass", "classical musician", "string player", "concert musician"],
    "founder": ["founder", "entrepreneur", "startup founder", "business owner", "co-founder", "solopreneur", "startup CEO", "small business owner"],
    # Batch 5 — new jobs from Supabase search gaps round 2 (2026-04-03)
    "professional-athlete": ["athlete", "professional athlete", "sports player", "footballer", "basketball player", "tennis player", "swimmer", "runner", "cricketer", "rugby player", "olympian", "sportsperson"],
    "composer": ["composer", "music composer", "film composer", "songwriter", "score composer", "music writer", "jingle writer", "orchestrator", "film scorer", "TV composer", "game composer"],
    "grant-writer": ["grant writer", "grants officer", "grants manager", "grant writing", "fundraiser", "grant coordinator", "proposal writer", "grants administrator", "development writer", "funding officer"],
    "embedded-systems-engineer": ["embedded systems engineer", "embedded engineer", "firmware engineer", "embedded developer", "embedded software engineer", "firmware developer", "embedded programmer", "IoT engineer", "microcontroller programmer", "RTOS developer", "embedded C developer"],
}

def main():
    with open("data/jobs.json") as f:
        jobs = json.load(f)

    for job in jobs:
        job_id = job["id"]
        terms = SEARCH_TERMS.get(job_id, [])
        # Always include the title itself as lowercase for matching
        job["searchTerms"] = terms

    with open("data/jobs.json", "w") as f:
        json.dump(jobs, f, indent=2)

    print(f"Added searchTerms to {len(jobs)} jobs")
    missing = [j["id"] for j in jobs if not j.get("searchTerms")]
    if missing:
        print(f"WARNING: {len(missing)} jobs have empty searchTerms: {missing}")

if __name__ == "__main__":
    main()
